// Generated by gencpp from file ros_basics_turorials/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_TURORIALS_MESSAGE_ADDTWOINTS_H
#define ROS_BASICS_TURORIALS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_basics_turorials/AddTwoIntsRequest.h>
#include <ros_basics_turorials/AddTwoIntsResponse.h>


namespace ros_basics_turorials
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_basics_turorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_basics_turorials::AddTwoInts > {
  static const char* value()
  {
    return "aa1aa1352f5bcf43b9b6f23761f75fd6";
  }

  static const char* value(const ::ros_basics_turorials::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_basics_turorials::AddTwoInts > {
  static const char* value()
  {
    return "ros_basics_turorials/AddTwoInts";
  }

  static const char* value(const ::ros_basics_turorials::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_basics_turorials::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_basics_turorials::AddTwoInts >
template<>
struct MD5Sum< ::ros_basics_turorials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_turorials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_turorials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_turorials::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_basics_turorials::AddTwoInts >
template<>
struct DataType< ::ros_basics_turorials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_basics_turorials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_turorials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_basics_turorials::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_basics_turorials::AddTwoInts >
template<>
struct MD5Sum< ::ros_basics_turorials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_basics_turorials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_turorials::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_basics_turorials::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_basics_turorials::AddTwoInts >
template<>
struct DataType< ::ros_basics_turorials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_basics_turorials::AddTwoInts >::value();
  }
  static const char* value(const ::ros_basics_turorials::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_BASICS_TURORIALS_MESSAGE_ADDTWOINTS_H
