// Generated by gencpp from file ros_basics_turorials/CustomMsg.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_TURORIALS_MESSAGE_CUSTOMMSG_H
#define ROS_BASICS_TURORIALS_MESSAGE_CUSTOMMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_turorials
{
template <class ContainerAllocator>
struct CustomMsg_
{
  typedef CustomMsg_<ContainerAllocator> Type;

  CustomMsg_()
    : id(0)
    , name()  {
    }
  CustomMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMsg_

typedef ::ros_basics_turorials::CustomMsg_<std::allocator<void> > CustomMsg;

typedef boost::shared_ptr< ::ros_basics_turorials::CustomMsg > CustomMsgPtr;
typedef boost::shared_ptr< ::ros_basics_turorials::CustomMsg const> CustomMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_turorials::CustomMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_turorials::CustomMsg_<ContainerAllocator1> & lhs, const ::ros_basics_turorials::CustomMsg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_turorials::CustomMsg_<ContainerAllocator1> & lhs, const ::ros_basics_turorials::CustomMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_turorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fe5a440459dcada9c353c016dfb49d2";
  }

  static const char* value(const ::ros_basics_turorials::CustomMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fe5a440459dcadaULL;
  static const uint64_t static_value2 = 0x9c353c016dfb49d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_turorials/CustomMsg";
  }

  static const char* value(const ::ros_basics_turorials::CustomMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string name\n"
;
  }

  static const char* value(const ::ros_basics_turorials::CustomMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_turorials::CustomMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_turorials::CustomMsg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_TURORIALS_MESSAGE_CUSTOMMSG_H
