// Generated by gencpp from file ros_basics_turorials/Localize.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_TURORIALS_MESSAGE_LOCALIZE_H
#define ROS_BASICS_TURORIALS_MESSAGE_LOCALIZE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_turorials
{
template <class ContainerAllocator>
struct Localize_
{
  typedef Localize_<ContainerAllocator> Type;

  Localize_()
    : Index(0)
    , Distance(0.0)
    , AoA(0.0)  {
    }
  Localize_(const ContainerAllocator& _alloc)
    : Index(0)
    , Distance(0.0)
    , AoA(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _Index_type;
  _Index_type Index;

   typedef double _Distance_type;
  _Distance_type Distance;

   typedef double _AoA_type;
  _AoA_type AoA;





  typedef boost::shared_ptr< ::ros_basics_turorials::Localize_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_turorials::Localize_<ContainerAllocator> const> ConstPtr;

}; // struct Localize_

typedef ::ros_basics_turorials::Localize_<std::allocator<void> > Localize;

typedef boost::shared_ptr< ::ros_basics_turorials::Localize > LocalizePtr;
typedef boost::shared_ptr< ::ros_basics_turorials::Localize const> LocalizeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_turorials::Localize_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_turorials::Localize_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_turorials::Localize_<ContainerAllocator1> & lhs, const ::ros_basics_turorials::Localize_<ContainerAllocator2> & rhs)
{
  return lhs.Index == rhs.Index &&
    lhs.Distance == rhs.Distance &&
    lhs.AoA == rhs.AoA;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_turorials::Localize_<ContainerAllocator1> & lhs, const ::ros_basics_turorials::Localize_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_turorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_turorials::Localize_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_turorials::Localize_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_turorials::Localize_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_turorials::Localize_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_turorials::Localize_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_turorials::Localize_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_turorials::Localize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bc0a38325dfefe892ff07d62efd38d8";
  }

  static const char* value(const ::ros_basics_turorials::Localize_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bc0a38325dfefe8ULL;
  static const uint64_t static_value2 = 0x92ff07d62efd38d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_turorials::Localize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_turorials/Localize";
  }

  static const char* value(const ::ros_basics_turorials::Localize_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_turorials::Localize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 Index\n"
"float64 Distance\n"
"float64 AoA\n"
"\n"
;
  }

  static const char* value(const ::ros_basics_turorials::Localize_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_turorials::Localize_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Index);
      stream.next(m.Distance);
      stream.next(m.AoA);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Localize_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_turorials::Localize_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_turorials::Localize_<ContainerAllocator>& v)
  {
    s << indent << "Index: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.Index);
    s << indent << "Distance: ";
    Printer<double>::stream(s, indent + "  ", v.Distance);
    s << indent << "AoA: ";
    Printer<double>::stream(s, indent + "  ", v.AoA);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_TURORIALS_MESSAGE_LOCALIZE_H
