#!/usr/bin/env python2
import rospy
import numpy as np
from ros_basics_turorials.msg import Localize

def Connection_callback:
  pass

def Localization_callback:
  pass

def Node_vehicle():
    global pub_Door, pub_Connection
    #Initialize
    rospy.init_node('node_Vehicle', anonymous=True)

    #Publish to
    pub_Door = rospy.Publisher('topic_Door', Localize, queue_size=10)
    pub_Connection = rospy.Publisher('topic_Connection', Localize, queue_size=10)

    #Subscribe to
    rospy.Subscriber('topic_Connection', Localize, Connection_callback)
    rospy.Subscriber('topic_Localization', Localize, Localization_callback)
    rospy.spin()

if __name__ == '__main__':
    Node_vehicle()
